### ISSUE TITLE
运行中意外退出

### ISSUE THREAD

**Issue by ShiinaMono** [dcyuki/yumemi_bot#2]
[2021-08-28T20:19:51.121] [DEBUG] [yumemi bot log] - Process GET /
[2021-08-28T20:19:51.181] [DEBUG] [yumemi bot log] - Process GET /error
[2021-08-28T20:19:51.281] [DEBUG] [yumemi bot log] - Process GET /favicon.ico
[2021-08-28T20:19:51.330] [DEBUG] [yumemi bot log] - Process GET /error
[2021-08-28T20:19:53.114] [DEBUG] [yumemi bot log] - Process GET /error
[2021-08-28T20:19:53.191] [DEBUG] [yumemi bot log] - Process GET /favicon.ico
[2021-08-28T20:19:53.249] [DEBUG] [yumemi bot log] - Process GET /error

检测到nginx使用80端口造成冲突，是否可以默认成其他端口

**Comment by ShiinaMono** [comment]
呃，有yml淦

**Comment by ShiinaMono** [comment]
[2021-08-28T20:47:52.095] [ERROR] [yumemi bot log] - Error: 请求失败，状态码: 404
    at ClientRequest.<anonymous> (/root/bot/yumemi_bot/dist/util.js:123:23)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:375:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)

改端口后报错

**Comment by xueelf** [comment]
> [2021-08-28T20:47:52.095] [ERROR] [yumemi bot log] - Error: 请求失败，状态码: 404
>     at ClientRequest.<anonymous> (/root/bot/yumemi_bot/dist/util.js:123:23)
>     at Object.onceWrapper (events.js:482:26)
>     at ClientRequest.emit (events.js:375:28)
>     at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
>     at Socket.socketOnData (_http_client.js:515:22)
>     at Socket.emit (events.js:375:28)
>     at addChunk (internal/streams/readable.js:290:12)
>     at readableAddChunk (internal/streams/readable.js:265:9)
>     at Socket.Readable.push (internal/streams/readable.js:204:10)
> 
> 改端口后报错

一直都有这个问题，我没做检测，这几个月写 [kokkoro](https://github.com/dcyuki/kokkoro) 去了，目前只有 `battle` 、 `guess` 和 `qa` 这三个插件会发送 http 请求读取数据库，在 `plugins/xxx/index.js` 最上面有一个 `url` 属性，做一下判断就行了，可以参考 `services/web/index.js` 下的逻辑做端口修改，不急的话也可以等我明天有时间改一下  
~~之前都是在群里口头叙述的，所以一直没管~~  
![3c6486b029d93963.jpg](https://user-images.githubusercontent.com/37479458/131221839-6fdc8d31-abe4-411e-a6e7-dbe11e89519c.jpg)

**Comment by ShiinaMono** [comment]
好的

**Comment by xueelf** [comment]
已修复
